groups:
  - name: demo-api-recording
    interval: 30s
    rules:
      - record: sre_demo:http_requests:rate5m
        expr: sum(rate(sre_demo_http_requests_total[5m]))

      - record: sre_demo:http_errors:ratio_rate5m
        expr: |
          sum(rate(sre_demo_http_requests_total{status_class="5xx"}[5m]))
          /
          clamp_min(sum(rate(sre_demo_http_requests_total[5m])), 0.000000001)

      - record: sre_demo:http_request_duration_seconds:p95_rate5m
        expr: |
          histogram_quantile(
            0.95,
            sum by (le) (rate(sre_demo_http_request_duration_seconds_bucket[5m]))
          )

      - record: sre_sli:probe_success:ratio_rate5m
        expr: avg_over_time(probe_success{job="blackbox-http",slo="availability"}[5m])

      - record: sre_sli:probe_duration_seconds:avg_rate5m
        expr: avg_over_time(probe_duration_seconds{job="blackbox-http",slo="availability"}[5m])
