global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: sre-control

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: demo-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - demo-api:8080
        labels:
          service: demo-api
          environment: lab

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
        - http_2xx
    file_sd_configs:
      - files:
          - targets/*.yml
        refresh_interval: 1m
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
